---
- name: install some useful packages 
  yum: name={{ item }} state=latest enablerepo=epel-testing
  with_items:
  - git
  - python-pip
  - unzip
  - python-psphere
  - ansible 

- name: download Tower setup
  get_url: url=http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{tower_version}}.tar.gz
    dest=/opt/ force=yes

- name: extract Tower
  command: chdir=/opt/ creates=/opt/ansible-tower-setup-{{tower_version}} tar zxvf ansible-tower-setup-{{tower_version}}.tar.gz

- name: run the Tower installer
  command: chdir=/opt/ansible-tower-setup-{{tower_version}} creates=/etc/awx/settings.py ./setup.sh

- name: set up private keys for demo boxes
  copy: src=id_rsa dest={{keydir}}/id_rsa mode=0600 owner=vagrant group=vagrant

- name: create etc ansible directory
  action: file dest={{configdir}} state=directory

- name: populate etc ansible hosts
  copy: src=hosts dest={{hostfile}}

- name: populate etc ansible config
  copy: src=ansible.cfg dest=/{{configdir}}

- name: Vagrant user demo playbook directory
  file: path=/home/vagrant/playbooks owner=vagrant group=vagrant mode=755 state=directory

- name: put lamp_haproxy example in user playbook dir
  git: repo={{ playbookrepo }} dest={{ userplaybookdir }} accept_hostkey=yes

- name: fix vagrant home permissions
  shell: sudo chown -R vagrant.vagrant /home/vagrant

- name: install tower cli
  shell: pip install ansible-tower-cli

- name: restart machine 
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  pause: seconds=30